from __future__ import annotations

from typing import Protocol


class MemoryCommandService(Protocol):
    async def list(self, args: str, *, chat_id: int, user_id: int | None = None) -> str: ...

    async def add(self, content: str, *, chat_id: int, user_id: int | None = None) -> str: ...

    async def search(self, query: str) -> str: ...

    async def delete(self, memory_id: int) -> str: ...

    async def stats(self) -> str: ...

    async def finalize(self, chat_id: int) -> str: ...


class KnowledgeCommandService(Protocol):
    async def list_states(self) -> str: ...

    async def status(self, chat_id: int) -> str: ...

    async def inspect(self, name: str | None = None) -> str: ...

    async def switch(self, chat_id: int, state_name: str) -> str: ...

    async def update(self, args: str) -> str: ...


class WatchCommandService(Protocol):
    async def list_monitors(self) -> str: ...

    async def run(self, name: str) -> str: ...

    async def pause(self, name: str) -> str: ...

    async def resume(self, name: str) -> str: ...
